baseURL = "https://machaon-dev.github.io/blog/"
languageCode = "ru-ru"
defaultContentLanguage = "ru"
title = "Machaon.Dev"
theme = "hugo-PaperMod"
enableEmoji = true
publishDir = "docs"

[params]
description = "Делимся полезным."
author = "Eugene Zadorin"
disableThemeToggle = true
#[params.homeInfoParams]
#Title = "Hello there 👽"
#Content = "Can be [Info](/test), links, about..."

[taxonomies]
tag = "tags"

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true

[menu]
  [[menu.main]]
    identifier = "team"
    name = "Team"
    url = "/tags/team/"
    weight = 10

  [[menu.main]]
    identifier = "code"
    name = "Code"
    url = "/tags/code/"
    weight = 20
